repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--safe, --line-length=100]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        args: [
          --fix,
          --select=E,
          --select=I,
          --select=T,
          --line-length=100
        ]
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff check
        args: [
          --select=E,
          --select=I,
          --select=T,
          --line-length=100
        ]
        language: system
        types: [python]
